# Generated by Django 3.2.6 on 2021-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.URLField(),
        ),
    ]
