# Generated by Django 3.2.6 on 2021-09-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0020_alter_lecture_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(max_length=2000, null=True),
        ),
    ]
