# Generated by Django 3.2.6 on 2021-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0021_auto_20210908_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='ldis',
            field=models.TextField(max_length=20000),
        ),
    ]
