# Generated by Django 3.2.6 on 2021-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.TextField(default=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.TextField(default=True, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.IntegerField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='course',
            field=models.TextField(max_length=1000),
        ),
    ]
