# Generated by Django 3.2.6 on 2021-08-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(default=True, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='education',
            field=models.CharField(default=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
