# Generated by Django 3.2.6 on 2021-08-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='messege',
            new_name='message',
        ),
    ]
