# Generated by Django 3.2.6 on 2021-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_rename_messege_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
