# Generated by Django 3.2.6 on 2021-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
