# Generated by Django 3.2.6 on 2021-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
