# Generated by Django 3.2.6 on 2021-09-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='course',
            new_name='mycourse',
        ),
    ]
